Feat add telegram bot
opennaslab/kubespider pull request #454
Opened 2024-02-08 09:24 UTC by acegao9527

**Release Note**

add send to telegram bot , trigger download

```release-note

```

2024-02-09 02:25 UTC, miRemid requested changes

2024-02-09 02:25 UTC, miRemid commented on kubespider/core/telegram_server.py
> +    )
这里条件分支漏了吧

2024-02-09 02:25 UTC, miRemid commented on kubespider/core/telegram_server.py
> +    event = Event(source, path)
Path最好指定一下

2024-02-09 02:25 UTC, miRemid commented on kubespider/core/telegram_server.py
> +    source = msg["text"]
这个source添加一个识别更好一点，例如判断字符串是否是下载链接（HTTP开头或magnet）

2024-02-09 15:32 UTC, acegao9527 commented on kubespider/core/telegram_server.py
> +    source = msg["text"]
好啊，发现这个telegram 的bot 项目有点老了，这几天换个依赖的项目

2024-02-10 02:03 UTC, acegao9527 commented on kubespider/core/telegram_server.py
> +    event = Event(source, path)
不指定使用默认，和httphook的逻辑保持一致

2024-02-10 02:05 UTC, acegao9527 commented on kubespider/core/telegram_server.py
> +    source = msg["text"]
后面的downloadtrigger.download_file()方法会判断，这里就不重复校验了，无脑转发，主体逻辑和webserver hook保持一致

2024-02-10 02:05 UTC, acegao9527 commented on kubespider/core/telegram_server.py
> +    )
已添加

2024-02-20 14:12 UTC, miRemid approved these changes

2024-02-20 14:12 UTC, merged